### ISSUE TITLE
Add support for cache eviction

### ISSUE THREAD

**Issue by atomb** [GaloisInc/argo#136]

**Comment by pnwamk** [comment]
See also https://github.com/GaloisInc/argo/issues/89 for some discussion on the topic.

**Comment by pnwamk** [comment]
Here is some initial tinkering aimed at limiting memory usage which aims to _"give users the option to save a result state, but ensure incremental states don't sit around eating up resources"_ (as suggested by @weaversa in https://github.com/GaloisInc/argo/issues/89): https://github.com/GaloisInc/argo/tree/feature/bounded-memory-usage

## Approach Details

In that branch, Argo essentially aims to guarantee a bound on memory use by:
+ keeping only the _initial_ server state cached indefinitely,
+ keeping alive a (customizable) number of recently used states while evicting others from the cache when it fills (along with any no longer in-use file contents loaded from disk), and 
+ allows states to be explicitly pinned in the cache, which would keep them in memory until they are explicitly unpinned.

The main cost of such an approach is that arbitrary states no longer in cache cannot be "replayed" or "resurrected" automatically when a request mentioning them is received once they are evicted (such a state would either have to be manually pinned or rebuilt by the client through standard interactions).

## Other memory leaks =\

Unfortunately some preliminary testing suggests we still have some memory leaks even with the aforementioned changes when we should be able to maintain a relatively constant memory footprint. 

E.g., under a heavy load from a single client which should not have required continual increases in memory usage, the following two server setups still resulted in _significant_ memory usage while the Python client app used a reasonable and seemingly bounded amount of memory:
+ `argo.RemoteSocketProcess('localhost', 50005, ipv6=True)`
+ `argo.DynamicSocketProcess("cabal v2-exec file-echo-api --verbose=0 -- socket --port 50005")`

and these two setups had less significant but still persistently increasing memory usage under those same circumstances:
+ `argo.HttpProcess(url="http://localhost:8080/")`
+ `argo.StdIOProcess("cabal v2-exec file-echo-api --verbose=0 -- stdio")`

I haven't had a chance to hunt down these other memory leaks just yet. I suppose it's possible some of it is due to leaks in the server app itself (i.e., in the `file-echo-api` server implementation used for the tests), but the drastic difference between the two setups seems to suggest there is definitely some leaking that still needs addressed in Argo proper.

## Remaining Questions

1. How important is the "guaranteed replayability" of past states for Argo? The [aforementioned approach](https://github.com/GaloisInc/argo/tree/feature/bounded-memory-usage) to limiting memory usage sets that feature aside to make things relatively simple... presumably there's a hybrid approach which supports some replayability while still bounding memory use. At the moment, however, (a) I don't think we have any use cases currently which require replayability (please correct me if I'm wrong there), and (b) some of our intended apps have backends that may already fundamentally struggle w.r.t. true replayability (e.g., Cryptol with [newtypes](https://github.com/GaloisInc/cryptol/pull/1015) and more advanced modules  begins to risk being non-replayable (although currently things may be structured in a deterministic/replayable enough way), and SAW may already be not entirely replaybable w.r.t. keeping in sync with an external user).

2. How important is truly bounded memory usage? Given that we're beginning to investigate loading these servers into some fairly constrained runtimes... I'm assuming having memory leaks will be a potentially frequent frustration going forward for users. But perhaps one could argue reducing leaks to a trickle and resetting the servers at regular intervals is good enough...? At the moment my personal bias is towards having explicit bounds/guarantees on memory usage... maybe that's just me though ¯\\\_(ツ)\_/¯

**Comment by pnwamk** [comment]
I updated the comments above regarding a possible memory leak with some actual GHC Heap profiling data. When being profiled the file-echo-api server seem more or less bounded in both cases.

**Comment by pnwamk** [comment]
There is now rudimentary support for bounded cache size, flushing caches, etc. If more complex support is desired we can open an issue then with those specific requirements.
