### ISSUE TITLE
client error recovery

### ISSUE THREAD

**Issue by pnwamk** [GaloisInc/argo#180]
Currently when an argo client errors the connection frequently becomes unusable, with any attempt at future interactions raising the same error.

This is because the RPC message containing the error is stored as the last [_raw_response](https://github.com/GaloisInc/argo/blob/ba47206518be32fa93befcb693509257d98af8f5/python/argo_client/interaction.py#L77) in the connection, and subsequent interactions with that connection internally query for the [state](https://github.com/GaloisInc/argo/blob/ba47206518be32fa93befcb693509257d98af8f5/python/argo_client/interaction.py#L162) of the connection (i.e., the state from which the new request will be made) which calls the `Command` objects [_result_and_state_and_out_err](https://github.com/GaloisInc/argo/blob/ba47206518be32fa93befcb693509257d98af8f5/python/argo_client/interaction.py#L140) method which sees the previous stored error and again raises the previous exception.

I think the correct solution is to be clear internally in the `Argo` server which exceptions are `recoverable` and which are `fatal`, and for `recoverable` exceptions the client should reset the "current state" to be what it was prior to the exception being raised, and for `fatal` exceptions (i.e., where the state for _some_ reason is corrupted, non-recoverable, etc) we should be clear about that and subsequent interactions with the connection should not re-raise the same error, but instead raise an error about the connection being/closed/reset/whatever.

For servers with immutable state, I think this should be fairly straightforward since the old state is not destroyed and the new state is not logged until [after the command](https://github.com/GaloisInc/argo/blob/ba47206518be32fa93befcb693509257d98af8f5/argo/src/Argo.hs#L872) is executed. I haven't thought much about mutable state servers... seems like there's only so much we can offer there - maybe we can let the server implementation themself worry about it with some callbacks...?

Anyway, here's a branch where I've got a minimal example test of an interaction after catching an exception that should work but does not currently: https://github.com/GaloisInc/argo/tree/feat/client-error-recovery

Whatever the solution is in `argo`, this should allow the related Cryptol issue to be solved: https://github.com/GaloisInc/cryptol/issues/1259

**Comment by m-yac** [comment]
The second paragraph is not quite right. Here's a fixed version:

This is because the connection saves the previous `Command` object as the `most_recent_result` of the connection, and has the result of its `protocol_state` method be the result of calling the [`state`](https://github.com/GaloisInc/argo/blob/ba47206518be32fa93befcb693509257d98af8f5/python/argo_client/interaction.py#L162) method of this object. Since this `state` method calls [`_result_and_state_and_out_err`](https://github.com/GaloisInc/argo/blob/ba47206518be32fa93befcb693509257d98af8f5/python/argo_client/interaction.py#L140), it will error if the result of the command is an error, and so in turn, the `protocol_state` method of the connection will also error whenever it's called after an erroring command is encountered by the connection. This `protocol_state` method is called [each time a new `Interaction` object is initialized](https://github.com/GaloisInc/argo/blob/05cbaf7e82f6b4b9badd637e424871697b860844/python/argo_client/interaction.py#L60), explaining why errors re-appear on subsequent interactions.

Note that this behavior (saving the previous interaction as `most_recent_result` and defining the `protocol_state` method in the stated way) is the case for the [`FileEchoConnection` class](https://github.com/GaloisInc/argo/blob/05cbaf7e82f6b4b9badd637e424871697b860844/python/tests/test_file_echo_interaction.py#L40) used in the linked example above, the Cryptol client and the SAW client, but is not required by argo.

A quick fix is to change the behavior of the `state` method of `Command` to simply return the last valid state (which is already saved) in the case of an error. This is done in #181.

**Comment by pnwamk** [comment]
Fixed by https://github.com/GaloisInc/argo/pull/181
