### ISSUE TITLE
State growth

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/argo#65]
Here I issued a slew of `load module` commands and we can see the state grow.

When in the interpreter, loading a module wipes the previous state (all let statements are gone, etc). Is there some reason the state grows here?

```
{ "result": { "state": [
 [ "load module", { "module name": "Primitive::Symmetric::Cipher::Block::AES" } ],
 [ "load module", { "module name": "Primitive::Symmetric::Cipher::Block::AES" } ],
 [ "load module", { "module name": "Primitive::Asymmetric::Signature::ECDSA::p521" } ],
 [ "load module", { "module name": "Primitive::Symmetric::Cipher::Block::AES" } ],
 [ "load module", { "module name": "Primitive::Asymmetric::Signature::ECDSA::p521" } ],
 [ "load module", { "module name": "Primitive::Symmetric::Cipher::Block::AES" } ],
 [ "load module", { "module name": "Primitive::Asymmetric::Signature::ECDSA::p521" } ] ]
```

**Comment by david-christiansen** [comment]
The reason is that the protocol can be seen as being in two layers:

 1. A general-purpose layer for building stateful interactions with arbitrary applications that uses caching to allow inexpensive roll-back to earlier states and exploration of related states

 2. An application layer that provides all the verbs for some particular system (in this case SAW or Cryptol, but perhaps other systems in the future if that becomes useful)

The caches from layer 1 form a conceptual tree, and the state representation on the wire right now is a path through that tree to a particular state, be it branch or leaf.

It seems reasonable to allow applications in layer 2 to do some path compression on the stored state. For instance, if a later command eliminates the effects of an earlier command, then it would be reasonable to drop the earlier one and add a shorter path through the tree of caches to the same cached state, and then return a representation of the compressed path to the client. But this path compression will be quite sensitive to the meanings of the different commands - for instance, changing a directory is only eliminated by a directory change immediately after it, with no intervening loads of files.

I wonder whether this is worth the complexity, however. It seems unlikely to me that the cost of transmitting a few module names won't be much smaller than the cost of the actual operations that the user wants to do in the module. Additionally, the user is free to discard a state and load a module in a previous state, which should not result in loss of cache.

**Comment by weaversa** [comment]
I see. So, the user should really be careful about how they manage the state. Some of my first tries at writing an interface involved something like this:

```
AESTest(state, key, pt) {
  state = load_module("Primitive::Symmetric::Cipher::Block::AES");                                                                                    
  evaluate_expression(call("aesEncrypt", argument(tuple(pt, key))));
}
```

Loading the module every time (and saving the new state) would create a huge state. Now that I know, I can do something different.
