### ISSUE TITLE
Increase cache performance from O(N^3) to O(N^2)

### ISSUE THREAD

**Issue by kwf** [GaloisInc/argo#71]
I think there is a more efficient way to implement IO-based cache invalidation, and I think it might be worthwhile to pursue. The current architecture for cache invalidation is to pass a single function to `historyWrapper` which tells it how to validate that a given state is still okay. This is exemplified in the `Main.hs` file for the SAW server:

```haskell
main :: IO ()
main =
  do initSt <- initialState
     cache  <- newCache initSt
     theApp <- mkApp (HistoryWrapper cache) (historyWrapper validateSAWState sawMethods)
     defaultMain description theApp
```

This current architecture re-runs the state validation function for every command—and it could not do any better, as currently designed, because an opaque single validation function must be checked against every intermediate state, lest one be invalid along the way.

However, in the common case where the state accumulates more and more information needing to be validated over time, this requires at worst N^2 time to compute, relative to the number of commands leading to a given state. In practice, this will actually be not N^2, but N^3, because in order to issue a causally sequential list of commands, each command in the sequence is given to the server as a pair of itself and its entire history—the validation of each taking take N^2 as above, and the execution of the whole sequence taking N^3 time as a result.

Because validation is a potentially expensive operation (involving reading from disk and hashing potentially large files), it seems important to minimize this asymptotic bound. One architecture to solve this problem would be to embed the validation actions `IO Bool` into the cache tree itself. This way, each individual state is paired with the `IO` action necessary to validate *only* the particular invariants needed by the single command that created this state from the previous one. In this way, a cache lookup consists of a sequence of non-overlapping validations, proceeding from the root of the tree to the located state, avoiding any redundant computation at nodes where validation must occur, and avoiding any validation computation at all at nodes requiring none. This brings the total complexity for executing a sequence of causally sequential list of commands down to N^2 in the number of things needing validation—the best we could hope for in such a stateless protocol without introducing something like a "do all these things at once then hand me the result" API.

As I see it, this change would require making the caching mechanism integrated into the `Method` monad, rather than a thing mixed in at the last minute, so that definitions in the `Method` monad can invoke a function `validate :: IO Bool -> Method state ()` to add their own custom validation logic. For instance, a method that loaded a file might, prior to its other activities, do something like:

```haskell
do snapshotHash <- hashFile path
   validate $ do
     currentHash <- hashFile path
     pure (snapshotHash == currentHash)
   -- actually load the file here --
```

When a method is invoked "for real" (that is, without a valid cached result), the monad would be able to collect all the `IO Bool` validators produced by calls to `validate`, embed them in the cache tree, and then use those in subsequent cache replays to make sure nothing needs to be recomputed.

One last thing: if caching is thus folded into `Method`, there still needs to be a way to indicate what constitutes a step down in the cache tree. I propose a second new operator in the `Method` monad:

```haskell
caching :: (Eq state, Hashable state) => Method state a -> Method state a
```

Depending on whether the current state is cached or not, this operation either executes the given method and adds new branches to the contained cache, or fast-forwards through the cache to the result. The equivalent to making an Argo app with a history wrapper around its state would be to have `mkApp` wrap each `Method` given to it in a call to `caching`, thus inserting a cache lookup point at each command invocation without any further ceremony.

**Comment by kwf** [comment]
If implemented, this would replace the implementation of #27 and , currently under review as #70.

**Comment by david-christiansen** [comment]
I have a somewhat more radical proposal.

State cache desiderata:

1. Each verb in the protocol should have a well-defined set of errors
   that it may return.

2. We should be able to define reasonable cache eviction strategies.

3. There should be a "small enough" overhead to restoring states from
   the cache.

4. It should be possible to efficiently branch the history, exploring
   multiple paths out of the same state, or backtracking a bit.

5. The "same" sequence of commands should yield the "same" state

6. State representations should be portable across process instances


Current solution:

1. Fails, because changes to files on disk may require re-loading
   them, which might throw errors from earlier replayed proof steps.

2. Succeeds - there seems to be little relationship between them.

3. Fails - see kwf's point about worst-case cubic complexity, and it
   may practically be n^2 (though with a very small constant factor,
   which means it might only manifest on very large workloads)

4. Succeeds

5. Succeeds

6. Succeeds, assuming they share a filesystem

New proposal:

The server maintains an explicit state object for each application,
the type of which is determined by the server itself. The server's
cache is a mapping from opaque identifiers (e.g. UUIDs) to state
objects. No attempt is made to ensure that side-effects are consistent
with the state of the world - if a file is loaded with contents A,
then it will have had contents A in every state caused by the state in
which it was loaded.

In the old system, because states were represented by recipes by which
they could be reconstituted, they could be evicted from the cache at
any time, and their most recent cached ancestor could recreate
them. This will not work in this system - either all states must be
cached, or users must otherwise indicate which are needed. If states
are not cached by default, then clients must use them linearly, so
errors will also need to return a state token.

Cache eviction can be restored, at the cost of some complexity for
clients, by adding specific messages that indicate to the server which
states the client is interested in saving. Experience with the Python
bindings shows that an explicit "checkpoint" message is a reasonably
convenient abstraction.

There seem to be two ways to indicate this:

 a. A field in messages that indicates whether its resulting state
    should be retained.

 b. A separate message, indicating that an already-seen state is to be
    retained.

The problem with option (a) is that the decision to save a state for
later might hinge on the result that gave rise to it.

I propose commands "retain" and "release". "retain" runs in a state,
and returns a fresh state token that can be referred to in the
future. "release" indicates a further lack of interest in the state,
making it no longer available. Retaining a retained state gives back a
fresh token that refers to the same state, and no token may be
released more than once (doing so is an error).

This requires clients to be explicit about caches, but we can build
the old behavior on top of it by retaining after each message and
having the client check file checksums.

With respect to the desiderata above:

 1. Succeeds. Each effectful method will either fail immediately or
    succeed eternally, and there is no replay.

 2. Succeeds, depending on whether you think offloading work to
    clients is "reasonable".

 3. Succeeds, at essentially O(1) with an appropriate data structure.

 4. Succeeds

 5. Does not succeed, but this seems to be a consequence of taking
    side effects seriously. There is no longer any notion of state
    equivalence.

 6. Fails. This desideratum may not be important, however.

What are your thoughts?

**Comment by david-christiansen** [comment]
(CC @atomb)

**Comment by weaversa** [comment]
Point 1 failed in the old method because 

roughly,
> In the old system, ... states were represented by recipes by which they could be reconstituted, but changes to files on disk may require re-loading them, which might throw errors from earlier replayed proof steps.

If the recipes included a hash of the files as they are loaded (including the prelude), wouldn't this protect against such errors?

About 2, I'm not convinced that relying on a user to remove things from the cache is a good idea --- this just seems like a memory leak waiting to happen. What is the eviction strategy for untidy users?

I like the new proposal because it is more efficient and the state is opaque to the user (the UUIDs). I think you could consider going one step further and making the state active only during a session. If a user disconnects (socket closes) the session and state are wiped. Perhaps the server could, upon request, send the client a kind of "cookie" containing a serialized dump of a state. Then, they could use it to reload their state in the future. Or even share it with others. I can easily imagine creating an issue here and uploading the cookie/state containing a replay of what was typed to provoke the issue (no more tar'ing misc. cry, saw, and bc files).

**Comment by david-christiansen** [comment]
Thanks for the feedback, @weaversa! I'll respond to points with individual comments, for the sake of keeping replies tractable.

> If the recipes included a hash of the files as they are loaded (including the prelude), wouldn't this protect against such errors?

This will not, because a hash is not sufficient to recover the contents of the file. The concern is this:

1. User writes a spec and creates a .bc file by running `make`

2. User loads both into SAW, which validates the spec, then gets distracted by a pretty bird out the window

3. Forgetting what they were doing, user tweaks their program and runs `make` again, introducing a bug

4. User changes working directory, and gets an error about a verification failure because SAW reloaded the .bc file

In one way, this makes sense - each command is asking the prover "does the world correspond to my thoughts". In another, it is deeply mysterious - why should changing directories cause verification failures?

I now suspect that the "right" way to ensure that the world is always consistent with the user's thoughts is something like CI, rather than arranging the protocol to do so on its own. This will also make interactive use more like existing tools, and make Jupyter interaction more predictable.

**Comment by david-christiansen** [comment]
> About 2, I'm not convinced that relying on a user to remove things from the cache is a good idea --- this just seems like a memory leak waiting to happen. What is the eviction strategy for untidy users?

I don't expect most users to be writing JSON messages with `netcat` - I expect them to be using bindings from a programming language.

I expect that most binding developers, should they expose the snapshot feature, will use features like finalizers or destructors to arrange for the cached objects to be released when their proxies in the language with bindings are deallocated/garbage collected.

**Comment by david-christiansen** [comment]
> I think you could consider going one step further and making the state active only during a session. If a user disconnects (socket closes) the session and state are wiped.

We can definitely support this if it's useful.

**Comment by david-christiansen** [comment]
> Perhaps the server could, upon request, send the client a kind of "cookie" containing a serialized dump of a state. Then, they could use it to reload their state in the future. Or even share it with others. I can easily imagine creating an issue here and uploading the cookie/state containing a replay of what was typed to provoke the issue (no more tar'ing misc. cry, saw, and bc files).

This would be a useful feature indeed, but I fear that it would be quite time-consuming to implement.

The state involved in these systems often includes higher-order data - for instance, the values of Cryptol functions are represented internally by Haskell functions. While it is usually possible to recover first-order serializable representations from this kind of data, I fear that it would be a large engineering effort.
